import React, { useState, useEffect, useRef } from 'react';
import { AppState, DocumentType, TemplateType, ResumeData } from './types';
import { INITIAL_DATA, MOCK_USER_DATA, THEME_COLORS, DEFAULT_NAME_CONFIG, DEFAULT_PHOTO_CONFIG } from './constants';
import Editor from './components/Editor';
import Preview from './components/Preview';
import { Download, Save, FolderOpen, FileText, ZoomIn, ZoomOut, Printer } from 'lucide-react';

// Helper to ensure loaded data has all necessary fields (backward compatibility)
// Defined outside component to be available for lazy state initialization
const sanitizeData = (data: any): ResumeData => {
  return {
    ...INITIAL_DATA,
    ...data,
    // Ensure config objects exist even if missing in old JSON
    photoConfig: { ...DEFAULT_PHOTO_CONFIG, ...(data.photoConfig || {}) },
    nameConfig: { ...DEFAULT_NAME_CONFIG, ...(data.nameConfig || {}) },
  };
};

const App: React.FC = () => {
  // Initialize state lazily from localStorage to prevent overwriting saved data on initial render
  const [state, setState] = useState<AppState>(() => {
    try {
      if (typeof window !== 'undefined') {
        const saved = localStorage.getItem('cv_forge_data_v2');
        if (saved) {
          const parsed = JSON.parse(saved);
          if (parsed.data) {
            return {
              docType: parsed.docType || DocumentType.RESUME,
              template: parsed.template || TemplateType.MODERN,
              themeColor: parsed.themeColor || THEME_COLORS[0].hex,
              data: sanitizeData(parsed.data),
              scale: 0.8 // Reset scale on reload
            };
          }
        }
      }
    } catch (e) {
      console.error("Failed to load data from local storage", e);
    }
    
    // Default fallback if no saved data found
    return {
      docType: DocumentType.RESUME,
      template: TemplateType.MODERN,
      themeColor: THEME_COLORS[0].hex,
      data: INITIAL_DATA,
      scale: 0.8
    };
  });

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Auto-save to local storage whenever state changes
  useEffect(() => {
    localStorage.setItem('cv_forge_data_v2', JSON.stringify({
      data: state.data,
      themeColor: state.themeColor,
      template: state.template,
      docType: state.docType
    }));
  }, [state.data, state.themeColor, state.template, state.docType]);

  const handleDataChange = (key: keyof ResumeData, value: any) => {
    setState(prev => ({
      ...prev,
      data: { ...prev.data, [key]: value }
    }));
  };

  const handleStateChange = (key: keyof AppState, value: any) => {
    setState(prev => ({ ...prev, [key]: value }));
  };

  // --- Features ---

  const handleDownloadJSON = () => {
    const dataStr = JSON.stringify(state.data, null, 2);
    const blob = new Blob([dataStr], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${state.data.fullName.replace(/\s+/g, '_')}_Resume_Data.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleLoadJSON = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const content = e.target?.result as string;
        const parsedData = JSON.parse(content);
        // Simple validation check
        if (parsedData.fullName !== undefined) {
            handleStateChange('data', sanitizeData(parsedData));
            
            // UX: Small delay to let React process, then confirm to user.
            setTimeout(() => {
                alert("Resume loaded successfully!");
            }, 100);
        } else {
            alert("Invalid file format. Please upload a JSON file generated by this app.");
        }
      } catch (err) {
        console.error("Error parsing JSON", err);
        alert("Failed to load file. Please check if it's a valid JSON.");
      }
    };
    reader.readAsText(file);
    // Reset input
    event.target.value = ''; 
  };

  const handleDownloadExample = () => {
    const dataStr = JSON.stringify(MOCK_USER_DATA, null, 2);
    const blob = new Blob([dataStr], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = "Resume_Example_Data.json";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Optional: Also load it into state for immediate view
    if (confirm("Download started! Do you also want to load this example into the editor now?")) {
        handleStateChange('data', sanitizeData(MOCK_USER_DATA));
    }
  };

  const handlePrintPDF = () => {
    // Add a small delay to allow the UI to update/settle before triggering the print dialog.
    setTimeout(() => {
      window.print();
    }, 100);
  };

  // Zoom Logic
  useEffect(() => {
    const handleWheel = (e: WheelEvent) => {
      if (e.ctrlKey) {
        e.preventDefault();
        const delta = e.deltaY * -0.001;
        setState(prev => ({
          ...prev,
          scale: Math.min(Math.max(prev.scale + delta, 0.4), 1.5)
        }));
      }
    };

    window.addEventListener('wheel', handleWheel, { passive: false });
    return () => window.removeEventListener('wheel', handleWheel);
  }, []);

  return (
    <div id="app-wrapper" className="flex flex-col h-screen text-slate-800 relative">
      
      {/* Top Bar - Increased z-index to 50 to ensure it's always on top */}
      <header className="bg-slate-900 text-white h-14 flex items-center justify-between px-6 shadow-md z-50 shrink-0 no-print relative">
        <div className="flex items-center gap-2">
           <div className="w-8 h-8 rounded flex items-center justify-center font-bold text-lg" style={{ backgroundColor: state.themeColor }}>C</div>
           <h1 className="font-bold text-lg tracking-tight">CV Forge</h1>
        </div>
        
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2 bg-slate-800 px-3 py-1 rounded-full border border-slate-700 zoom-controls hidden md:flex">
            <button onClick={() => handleStateChange('scale', Math.max(state.scale - 0.1, 0.4))} className="hover:text-indigo-400"><ZoomOut size={16} /></button>
            <span className="text-xs font-mono min-w-[3ch] text-center">{Math.round(state.scale * 100)}%</span>
            <button onClick={() => handleStateChange('scale', Math.min(state.scale + 0.1, 1.5))} className="hover:text-indigo-400"><ZoomIn size={16} /></button>
          </div>

          <div className="h-6 w-px bg-slate-700 mx-1 hidden md:block"></div>

          <button 
             onClick={() => fileInputRef.current?.click()}
             className="flex items-center gap-2 px-3 py-1.5 rounded text-sm hover:bg-slate-800 text-slate-300 hover:text-white transition-colors"
             title="Upload JSON File"
          >
            <FolderOpen size={16} /> <span className="hidden sm:inline">Load JSON</span>
          </button>
          <input 
            type="file" 
            ref={fileInputRef} 
            className="hidden" 
            accept=".json" 
            onChange={handleLoadJSON} 
          />

          <button 
             onClick={handleDownloadJSON}
             className="flex items-center gap-2 px-3 py-1.5 rounded text-sm hover:bg-slate-800 text-slate-300 hover:text-white transition-colors"
             title="Save Progress"
          >
            <Save size={16} /> <span className="hidden sm:inline">Save JSON</span>
          </button>
          
          <button 
             onClick={handleDownloadExample}
             className="flex items-center gap-2 px-3 py-1.5 rounded text-sm hover:bg-slate-800 text-slate-300 hover:text-white transition-colors"
             title="Download Example Data"
          >
            <FileText size={16} /> <span className="hidden sm:inline">Example</span>
          </button>

          <button 
             onClick={handlePrintPDF}
             className="flex items-center gap-2 px-4 py-1.5 rounded text-sm font-medium text-white transition-colors shadow-sm hover:shadow-md active:translate-y-0.5"
             style={{ backgroundColor: state.themeColor }}
          >
            <Printer size={16} /> Print / PDF
          </button>
        </div>
      </header>

      {/* Main Workspace - z-0 to stay below header */}
      <main className="flex-1 flex overflow-hidden z-0">
        
        {/* Left: Editor */}
        <aside className="w-[450px] min-w-[350px] max-w-[500px] h-full flex-shrink-0 border-r border-slate-200 z-10">
          <Editor state={state} onChange={handleDataChange} onStateChange={handleStateChange} />
        </aside>

        {/* Right: Preview */}
        <section className="preview-container flex-1 bg-slate-200/50 relative overflow-hidden flex flex-col z-0">
          <div className="print-break-fix flex-1 overflow-auto relative custom-scrollbar flex justify-center py-10 bg-slate-200/50">
             <Preview 
                data={state.data}
                template={state.template}
                type={state.docType}
                scale={state.scale}
                themeColor={state.themeColor}
             />
          </div>
          
          <div className="absolute bottom-4 right-4 bg-white/80 backdrop-blur px-3 py-1 rounded-full shadow border text-xs text-slate-500 pointer-events-none no-print">
            Hold Ctrl + Scroll to Zoom
          </div>
        </section>

      </main>
    </div>
  );
};

export default App;